### ISSUE TITLE
Templates folder not created with pip install

### ISSUE THREAD

**Issue by Geocali** [andreasgerstmayr/fava-income-reports#1]
Thanks for this nice project ! 

I have some troubles installing it:

Using the command `pip install git+https://github.com/andreasgerstmayr/fava-income-reports.git` does create the contents of the `templates` folder in `site-packages/fava_income_reports`.

The only files present are `monthly_pnl.py` and `sankey.py`

Do you know why the files in `fava_income_reports/templates` have not been copied ?

This part is probably missing from `pyproject.py` (https://setuptools.pypa.io/en/latest/userguide/quickstart.html#automatic-package-discovery) 

```
[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters
```

**Comment by andreasgerstmayr** [comment]
@Geocali thanks! and thanks for reporting this issue.

I've forgot to add `include_package_data = True`, therefore the package only included the python files and no other files (like the html templates). It should work now.

I missed that because personally I installed the package by cloning the git repository and installing it with `pip install -e` for local development.
